version: '3.1'
services:
  app:
    build: . 
    volumes:
      - ./src:/app
      - ./in:/in
      - ~/ourci/applogs:/app/tmp
    command: 'sh -c "sleep 15 ; python3 /app/Billing.py"'
    ports:
      - 8000:5000
    environment:
      WEIGHT_ADDRESS: "http://104.154.189.213:3000"
      # WEIGHT_ADDRESS: "http://192.168.8.112:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: billdb
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./sqldata:/docker-entrypoint-initdb.d
