version: '3.1'
services:
  app:
    build: . 
    volumes:
      - ./src:/app
      - ./in:/in
    command: 'sh -c "sleep 15 ; python3 /app/app.py"'
    ports:
      - 9090:9090
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: weight
      MYSQL_ROOT_PASSWORD: 123@admin
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      
